# Generated by Django 3.0.5 on 2020-04-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/products/%Y/%m/%d'),
        ),
    ]
