# Generated by Django 3.0.4 on 2020-06-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_quantity'),
        ('shop', '0002_product_quantity'),
    ]

    operations = [
    ]
